apiVersion: v1
entries:
  connaisseur:
  - apiVersion: v2
    appVersion: 2.7.0
    created: "2023-02-18T19:40:42.134246-06:00"
    description: Helm chart for Connaisseur - a Kubernetes admission controller to
      integrate container image signature verification and trust pinning into a cluster.
    digest: 9ac2a8f4862ab108898e72a2e478affef77449be3eaa17071883693c79c86b3e
    home: https://sse-secure-systems.github.io/connaisseur/latest
    icon: https://raw.githubusercontent.com/sse-secure-systems/connaisseur/master/docs/assets/logo.svg
    keywords:
    - container image
    - signature
    - verification
    maintainers:
    - email: philipp.belitz@securesystems.de
      name: Philipp Belitz
    - email: christoph.hamsen@securesystems.de
      name: Christoph Hamsen
    - email: peter.thomassen@securesystems.de
      name: Peter Thomassen
    name: connaisseur
    sources:
    - https://github.com/sse-secure-systems/connaisseur
    type: application
    urls:
    - https://s3b4sz17.github.io/connaisseur/helm/connaisseur-1.5.0.tgz
    version: 1.5.0
generated: "2023-02-18T19:40:42.133042-06:00"
